// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Survey actions
export const SAVE_SURVEY = 'SAVE_SURVEY';
export const HOUSE_CREATED_SUCCESS = 'HOUSE_CREATED_SUCCESS';
export const FETCH_HOUSE_SUCCESS = 'FETCH_HOUSE_SUCCESS';
export const FETCH_HOUSE_ERROR = 'FETCH_HOUSE_ERROR';

export const LOAD_FORM = 'LOAD_FORM';

